version: "3.7"

services:
  ourplace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:rc-alpine
