version: "3.7"

services:
  ourplace:
    volumes:
      - type: bind
        source: ./media
        target: /media
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
